### ISSUE TITLE
Slicing signed bit vector triggers assert

### ISSUE THREAD

**Issue by nxmq** [YosysHQ/yosys#2851] opened 2021-06-30 19:45 UTC
## Steps to reproduce the issue

1. feed yosys the following verilog via `read_verilog`:

```verilog
module a ();
    wire signed [1:0] b;
    c c(b[1:0]);
endmodule
```

2. `read_verilog` fails with the message:

```ERROR: Assert `arg->is_signed == sig.as_wire()->is_signed' failed in frontends/ast/genrtlil.cc:1865.```

This assert is not triggered if b is not declared as signed, if the indexing is removed from b in the module instantiation, or if the size of the slice of b is reduced to 1.

## Expected behavior

The verilog snippet above should be parsed successfully.

## Actual behavior

Assert triggered in genrtlil.cc

**Comment by zachjs** [comment] 2021-06-30 20:18
I believe this is a duplicate of #2654, which has a pending fix in #2716. Can you confirm?

**Closed** 2021-07-13 04:10 UTC
Labels: duplicate
