### ISSUE TITLE
Cannot pass memories in as module ports

### ISSUE THREAD

**Issue by hughperkins** [YosysHQ/yosys#3230] opened 2022-03-13 12:40 UTC
## Steps to reproduce the issue

try to synthesize the following code:

```
module proc_reg_wr_mux(
    input clk, rst,
    input [4:0] reg_sel[num_ports],
    input [31:0] data[num_ports],
    input req [num_ports],
    output reg ack [num_ports],
);
    parameter num_ports = 3;
endmodule
```

## Expected behavior

Synthesize ok. (eg simulators verilator and iverilog both accept this syntax.)

Why we might want to use this syntax? e.g. https://electronics.stackexchange.com/a/190809/307376

## Actual behavior

yosys crashes with

```
src/proc_reg_wr_mux.sv:3: ERROR: syntax error, unexpected '[', expecting ',' or '=' or ')'
```

**Comment by zachjs** [comment] 2022-03-14 23:18
This is a duplicate of #2717.

**Closed by zachjs** 2022-03-14 23:18 UTC
