### ISSUE TITLE
Why Uniqueness Constraints are not used in Yosys' K-Induction script to solve the problem of UNKNOWN due to Unreachable loop of good states?

### ISSUE THREAD

**Issue by shubam7809** [YosysHQ/yosys#3466] opened 2022-08-30 09:03 UTC
### Discussed in https://github.com/YosysHQ/yosys/discussions/3465

<div type='discussions-op-text'>

<sup>Originally posted by **shubam7809** August 30, 2022</sup>
Hello
I have a query related to Yosys implementation of K-Induction Algorithm. I will be grateful if someone (especially Clifford Wolf) could help me. 
I have been using Yosys for a while to do the Formal Verification of some VHDL designs using PSL assertions. I observed that K-Induction is showing “UNKNOWN” most of the times for my designs. It is probably due to the unreachable loop(s) of good states followed by a reachable bad state in the state space that Clifford Wolf have explained in one of his seminars on Yosys. As you must already know, adding addition assertions to break those loops is a strenous process. I wonder why have he not put any Uniqueness Constraints in Yosys K-Induction script to encounter this problem.

Thanks</div>

**Comment by jix** [comment] 2022-08-30 10:42
Duplicate of https://github.com/YosysHQ/yosys/discussions/3465

**Closed by jix** 2022-08-30 10:42 UTC
