### ISSUE TITLE
Memory changes without a clock edge

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#465] opened 2017-12-05 21:35 UTC
See the example [here](http://zipcpu.com/tmp/ybug7.tgz).  It's of an [SDRAM controller](https://github.com/ZipCPU/xulalx25soc/blob/master/rtl/wbsdram.v).  In the example, though, some of the bank state information (kept in a memory structure) changes apart from a clock pulse changing it.

Dan

**Comment by cliffordwolf** [comment] 2019-05-04 06:53
Closing because example download link is now broken, i.e. can't reproduce.

**Closed by cliffordwolf** 2019-05-04 06:53 UTC
