### ISSUE TITLE
[Bug] `yosys.exe` doesn't output anything on Windows 10 Pro

### ISSUE THREAD

**Issue by pidgeon777** [YosysHQ/yosys#4005] opened 2023-10-12 13:30 UTC
I'm running this command:

```
yosys.exe xxx
```

The problem is that no matter which argument I use, `yosys` doesn't output anything.

I installed this Windows release with `scoop`:

https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2023-10-12

My OS is Windows 10 Pro.

**Comment by mmicko** [comment] 2023-10-12 14:07
Duplicate of https://github.com/YosysHQ/oss-cad-suite-build/issues/83

**Closed by mmicko** 2023-10-12 14:07 UTC
