### ISSUE TITLE
Please support BUFT cell types for xilinx architecture. 

### ISSUE THREAD

**Issue by SergeyDegtyar** [YosysHQ/yosys#1388] opened 2019-09-20 11:17 UTC
## Steps to reproduce the issue

module tristate (en, i, o);
    input en;
    input i;
    output reg o;
    
    always @(en or i)
		o <= (en)? i : 1'bZ;

endmodule

module top (
input en,
input a,
output b
);

tristate u_tri (
        .en (en ),
        .i (a ),
        .o (b )
    );

endmodule

read_verilog tribuf.v
proc
tribuf
synth_xilinx

## Expected behavior

  Number of cells:                  1
     $_TBUF_                         1

## Actual behavior

   Number of cells:                  1
     BUFT                                1

**Comment by koriakin** [comment] 2019-09-21 15:43
Duplicate of #1225

**Closed by koriakin** 2019-09-21 15:43 UTC
