### ISSUE TITLE
Signal [1] is defined more than once. (Example included) #628

### ISSUE THREAD

**Issue by qaarah** [YosysHQ/yosys#629] opened 2018-09-14 13:48 UTC
Extension to issue #628 #622 
Source verilog file: 
http://www.clifford.at/papers/2016/malicious-lut/example.v

Expected blif format that abc can read and compute  Miter. 
Thanks 
@cliffordwolf  I am sorry for inconvenience. I should have given the source verilog.

**Comment by cliffordwolf** [comment] 2019-03-09 22:52
I can't reproduce any issue with the information provided here and in #628 and #622. Using current git head:

```
$ yosys -qp "hierarchy; proc -global_arst reset; flatten; techmap; ice40_unlut; opt_clean; abc -script +strash;ifraig;scorr;retime;strash; clean; write_blif example.blif" example.v 

$ yosys-abc 
UC Berkeley, ABC 1.01 (compiled Mar  7 2019 08:49:50)
abc 01> read_blif example.blif
abc 02> ***EOF***

$ yosys-abc 
UC Berkeley, ABC 1.01 (compiled Mar  7 2019 08:49:50)
abc 01> miter example.blif example.blif
abc 02> ***EOF***
```

So I'm closing this issue now.

I don't know what expectations OP has here, considering that the issue neither contains the ABC error message they see, nor the ABC commands they run. Obviously it's hard to reproduce anything without this kind of information.

**Closed by cliffordwolf** 2019-03-09 22:52 UTC
