### ISSUE TITLE
Assert `!w->port_input` failed in passes/techmap/abc9.cc:97

### ISSUE THREAD

**Issue by norandomtechie** [YosysHQ/yosys#1487] opened 2019-11-12 14:12 UTC
## Steps to reproduce the issue

Given a file called [simple_computer.txt](https://github.com/YosysHQ/yosys/files/3836471/simple_computer.txt) (originally called simple_computer.v but GitHub doesn't like the .v extension) that implements a very simple computer including a register file, ALU, RAM, and IDMS, we attempted synthesis using the following command.

`yosys -p "synth_ice40 -abc9 -top top; write_verilog struct_simpcomp.v" simple_computer.v`

This was with Yosys 0.9+932 (git sha1 3c6a566d, gcc 6.3.0-18+deb9u1 -fPIC -Og).

## Expected behavior

We expected the design to fully synthesize and output a Verilog file in structural format that is used later for gate-level synthesis of the original design.

## Actual behavior

I get the following assertion error:

```
2.43. Executing ABC9 pass (technology mapping using ABC9).

2.43.1. Extracting gate netlist of module `\top' to `<abc-temp-dir>/input.xaig'..

2.43.1.1. Executing SCC pass (detecting logic loops).
Found an SCC: $techmap$auto$simplemap.cc:517:simplemap_dlatch$5921.$auto$simplemap.cc:277:simplemap_mux$25512
....
Found an SCC: $techmap$auto$simplemap.cc:517:simplemap_dlatch$6009.$auto$simplemap.cc:277:simplemap_m
Found 56 SCCs in module top.
Found 56 SCCs.
ERROR: Assert `!w->port_input' failed in passes/techmap/abc9.cc:97.
```

**Comment by daveshah1** [comment] 2019-11-12 14:20
I think this is a duplicate of #1415 - there is a bug in how the abc9 command attempts to remove combinational loops before creating the loop-free AIG. Are the latches in your design intentional or unintentional? In the latter case the best fix would be to remove them.

**Closed** 2019-12-02 10:20 UTC
Labels: duplicate
