### ISSUE TITLE
Signal [1] is defined more than once. 

### ISSUE THREAD

**Issue by qaarah** [YosysHQ/yosys#628] opened 2018-09-14 10:41 UTC
Hi, 
I would like to provide some details. 
I am using the following script to synthesize the circuit to generate the blif file. 
**yosys -p "hierarchy; proc -global_arst reset; flatten;  techmap; ice40_opt -unlut; opt_clean; abc -script +strash;ifraig;scorr;;retime;strash; clean; write_blif"**

I get the following blif file. 
model example
.inputs a
.outputs zro_zro zro_not zro_buf zro_one not_zro not_not not_buf not_one buf_zro buf_not buf_buf buf_one one_zro one_not one_buf one_one magic_inverter
.names $false
.names $true
1
.names $undef
.names a inverter
0 1
.names a buf_buf
1 1
.names a buf_not
1 1
.names a buf_one
1 1
.names a buf_zro
1 1
.names inverter not_buf
1 1
.names inverter not_not
1 1
.names inverter not_one
1 1
.names inverter not_zro
1 1
.names $true one_buf
1 1
.names $true one_not
1 1
.names $true one_one
1 1
.names $true one_zro
1 1
.names $false zro_buf
1 1
.names $false zro_not
1 1
.names $false zro_one
1 1
.names $false zro_zro
1 1
.end
For Miter computation using ABC I give this blif file to abc, I am facing the error Line 6: Signal "[1]" is defined more than once.

I hope I may be able to make this issue understandable.
Thanks @cliffordwolf in advance. If you require anything else, please do let me know, I would like to email you. 
Thanks

**Comment by cliffordwolf** [comment] 2018-09-14 12:01
The issue template asked you to provide "Steps to reproduce the issue". You didn't. (You did not provide the Verilog input you are using.) I'm, not sure what your expectations is, but obviously I can't do anything if I can't reproduce the issue, so I'm closing this now.

**Closed by cliffordwolf** 2018-09-14 12:01 UTC
