### ISSUE TITLE
Yosys issue error in propagating golbal typdedef from one file to other file:  ERROR: syntax error, unexpected ';', expecting '(' or '['

### ISSUE THREAD

**Issue by dineshannayya** [YosysHQ/yosys#2664] opened 2021-03-15 15:05 UTC
Note: With latest yosys release has fixed propagating global parameter from one file to other file. But showing issue in propagating typedef function from one file to other [file.]

## Steps to reproduce the issue
Tested in latest Yosys release: 0.9+4008 (git sha1 e178d036, clang 10.0.0-4ubuntu1 -fPIC -Os)

yosys> read_verilog -sv a1.sv
    Parsing SystemVerilog input from `a1.sv' to AST representation.
    Generating RTLIL representation for module `\a1'.
    Successfully finished Verilog frontend.

yosys> read_verilog -sv b1.sv

Parsing SystemVerilog input from `b1.sv' to AST representation.
b1.sv:11: ERROR: syntax error, unexpected ';', expecting '(' or '['

## Expected behavior

Expected behaviour was global typedef defined in previous file should have propagated to next file
Actual behavior

## Actual behavior

Tool is issue warning:
ERROR: syntax error, unexpected ';', expecting '(' or '['

Attached the Example file and run command

[issue.tar.gz](https://github.com/YosysHQ/yosys/files/6142332/issue.tar.gz)

**Comment by zachjs** [comment] 2021-03-15 16:20
This is a duplicate of https://github.com/YosysHQ/yosys/issues/2440.

**Closed by zachjs** 2021-03-15 16:20 UTC
