### ISSUE TITLE
CXXRTL: assert on nets with multiple drivers

### ISSUE THREAD

**Issue by tomverbeure** [YosysHQ/yosys#2374] opened 2020-09-04 23:02 UTC
## Steps to reproduce the issue

[endless_toggle.zip](https://github.com/YosysHQ/yosys/files/5177255/endless_toggle.zip)

Verilog design with combinational feedback loop:

```verilog
module endless_toggle(input clk1);

    wire toggle = 0;
    wire taggle;

    assign taggle = ~toggle;
    assign toggle = taggle;

endmodule
```

```
yosys -p "read_verilog endless_toggle.v; hierarchy -top endless_toggle; write_cxxrtl endless_toggle.cpp"
```

```
 Yosys 0.9+3565 (git sha1 474cd02e, clang 11.0.0 -fPIC -Os)
```
## Expected behavior

CXXRTL does something that doesn't crash. Error message or C code.

## Actual behavior

```
ERROR: Assert `flow.wire_comb_defs[wire].size() == 1' failed in backends/cxxrtl/cxxrtl_backend.cc:2185.
```

It's obviously a nonsense design, but chances are that this assert would trigger valid designs as well.

**Comment by tomverbeure** [comment] 2020-09-04 23:06
When removing the `= 0` in the `wire toggle = 0;`, it compiles fine.

**Comment by whitequark** [comment] 2020-09-04 23:09
Oh right, that's invalid Verilog, it has multiple drivers for `toggle`.

**Comment by whitequark** [comment] 2020-09-04 23:09
I guess I can still add a check for that, not too hard.

**Comment by tdaede** [comment] 2020-09-13 02:34
I just got the same assert with cxxrtl and ao68000: https://gitlab.com/Chips4Makers/ao68000

It's possible this design has such a feedback loop, I'll see if I can find any obvious ones.

**Comment by tdaede** [comment] 2020-09-22 07:19
I found a minimal reproducer for my assert. The problem is code I added to initialize some memories which reuses the same integer for both initialization loops. Removing the second loop, or adding a second integer j and using that for the second loop, avoids the assert.

```
module memory_registers(

);


// Generic version of A register bank
reg [31:0] An[0:7];

integer i;
initial begin
    for (i = 0; i < 8; i = i + 1) begin
        An[i] = 0;
    end
end


// Generic version of D register bank
reg [31:0] Dn[0:7];

initial begin
    for (i = 0; i < 8; i = i + 1) begin
        Dn[i] = 0;
    end
end


endmodule
```

**Comment by whitequark** [comment] 2020-11-01 11:50
> Removing the second loop, or adding a second integer j and using that for the second loop, avoids the assert.

Yeah, this module is driving `i` twice. Your issue is arguably a frontend bug though.

**Comment by whitequark** [comment] 2020-11-01 12:50
Will be fixed by https://github.com/YosysHQ/yosys/pull/2424 and print:

```
ERROR: Wire endless_toggle.toggle has multiple drivers.
```

**Closed** 2020-11-01 13:53 UTC
Labels: bug
