### ISSUE TITLE
Bug with modulo in CXXRTL when operands intersect

### ISSUE THREAD

**Issue by flaviens** [YosysHQ/yosys#4112] opened 2024-01-06 17:37 UTC
### Version

Yosys 0.29+11 (git sha1 0b05a6425, gcc 7.5.0-6ubuntu2 -fPIC -Os), also reproduced in
Yosys 0.29+11 (git sha1 f7ffd12bf, gcc 7.5.0-6ubuntu2 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

Hi there!

I noticed that the modulo operation sometimes provides wrong results in CXXRTL when there is an intersection between the operands.

#### Design

For example, this design, supplied with `in_data=0x216231b1f16e9e8`:
```
module top(
    input logic [63:0] in_data,
    output logic [63:0] out_data
);
    assign out_data = in_data[41:6] % in_data[63:28];
endmodule
```

Some valuations of `in_data` yield a correct result and seem to compute faster than faulty valuations.

When there is no intersection between the operands, it seems that the calculation is correct, for example:
```
module top(
    input logic [63:0] in_data,
    output logic [63:0] out_data
);
    assign out_data = in_data[63:32] % in_data[31:0];
endmodule
```

#### Testbench

The testbench can look like this: `tb_cxxrtl.cc`:

```
#include "top.cpp"

int main() {
    cxxrtl_design::p_top top;
    uint64_t in_data=0x216231b1f16e9e8;
    top.p_in__data.set<uint64_t>(in_data);
    top.step();
    uint64_t out_val = top.p_out__data.get<uint64_t>();
    std::cout << "Out data: " << std::hex << out_val << std::endl;
}
```

#### Commands

```
yosys -p "read_verilog -sv top.sv; write_cxxrtl top.cpp"
g++ -g -O3 -std=c++14 -I `yosys-config --datdir`/include tb_cxxrtl.cc -o tb
./tb
```

Thanks!
Flavien

### Expected Behavior

Output value: `0x35522118`

### Actual Behavior

Output value: `0x90beaf8`

**Comment by whitequark** [comment] 2024-01-06 19:11
You must post the complete reproduction steps, not just your Verilog code.

**Comment by flaviens** [comment] 2024-01-06 19:34
Hi @whitequark, thank you for your quick response! I adapted the post according to your feedback. Please let me know if you would like more information!

**Comment by povik** [comment] 2024-01-08 12:41
I think `0x90beaf8` is expected, at least that's what I get with
```
yosys -p "read_verilog -sv top.sv; eval -set in_data 64'h216231b1f16e9e8 w:out_data"
```
Though there's still a discrepancy, since CXXRTL gives me `0x435522118`.

**Comment by whitequark** [comment] 2024-01-19 23:21
@flaviens I cannot reproduce this, and the condition ("intersection between operands") doesn't even make sense. `0x90beaf8` is the correct result.

```
>>> hex((0x216231b1f16e9e8>>6) & ((1 << (41-6+1))-1))
'0xc6c7c5ba7'
>>> hex((0x216231b1f16e9e8>>28) & ((1 << (63-28+1))-1))
'0x216231b1'
>>> hex(0xc6c7c5ba7 % 0x216231b1)
'0x90beaf8'
```

**Comment by whitequark** [comment] 2024-01-20 00:26
This was probably fixed by commit https://github.com/YosysHQ/yosys/commit/ded63bedd589255e6e06747edcdbf262444ac379 and/or https://github.com/YosysHQ/yosys/commit/ff53f3d2b6e267358cf4c3d08574416c79441ef9 and/or https://github.com/YosysHQ/yosys/commit/d7cb6981b55a15eee3d0d9be84446826a65c0403.

**Closed by whitequark** 2024-01-20 00:26 UTC
Labels: pending-verification, cxxrtl
