### ISSUE TITLE
write_cxxrtl crashes with assertion failure on $meminit cells with non-constant ADDR/DATA

### ISSUE THREAD

**Issue by dan-rodrigues** [YosysHQ/yosys#2129] opened 2020-06-09 10:06 UTC
As requested:

## Steps to reproduce the issue

`yosys -p 'read_ilang ics32_ilang; write_cxxrtl -O0 sim.cpp'`

Using the following as input:
[ics32_ilang.zip](https://github.com/YosysHQ/yosys/files/4751382/ics32_ilang.zip)

## Expected behavior

Outputs sim.cpp without error

## Actual behavior

```
ERROR: Assert `is_fully_const() && GetSize(chunks_) <= 1' failed in kernel/rtlil.cc:3801.`
```

## Version

Yosys built from c172b30c24285faa2b57f84a2a5162c5f3dcfb4c

**Comment by whitequark** [comment] 2020-06-09 10:08
This has no bearing on this issue (it is clearly a bug) but please note that using levels lower than `-O2` with cxxrtl has virtually no benefits and it will cause the generated C++ to stress your C++ compiler a lot.

**Comment by whitequark** [comment] 2020-06-09 11:57
The direct cause of the issue is that some `$meminit` cells did not have constant address/data due to the specific script used. Of course this shouldn't assert. But I'm not sure where the code to check for that should live; right now it's in `memory_collect`, but cxxrtl specifically does *not* want `$mem` cells. @clairexen opinions?

**Comment by whitequark** [comment] 2020-11-01 15:27
Will be fixed by #2425 and print:

```
ERROR: Non-constant address $memwr$\alpha_lut$vdp/vdp_blender.v:70$2783_ADDR in memory initialization $meminit$\alpha_lut$vdp/vdp_blender.v:0$3068.
```

**Comment by whitequark** [comment] 2020-11-01 15:27
(The message isn't super great but any fix should be in the common memory code so that non-cxxrtl users benefit from it as well.)

**Comment by mwkmwkmwk** [comment] 2020-11-01 15:55
Also FYI: the solution here (assuming the input is valid in the first place) is to run `opt_expr` to perform missing constant folding before running the backend.

**Closed** 2020-11-01 17:08 UTC
Labels: bug
