### ISSUE TITLE
package import issue

### ISSUE THREAD

**Issue by gkamendje** [YosysHQ/yosys#2187] opened 2020-06-24 06:50 UTC
## Steps to reproduce the issue
In the file my_pkg.sv I have the following

package my_pkg;
       parameter KL=64;
endpackage

in the file top.sv I have the following
import my_pkg::*;
module top(
        input logic i_clk,
        output logic o_done
);
endmodule

## Expected behavior
The tool should accept the top level file since it is a valid syntax. This is a common way to import all the content of a package inside a module and hence avoid having to prefix the package name every time a package parameter is used inside the module. This works in Modelsim, VCS as well as in DC. Is there a way to accomplish this in Yosys?
## Actual behavior

top.sv:1: ERROR: syntax error, unexpected TOK_ID

**Comment by zachjs** [comment] 2020-08-01 00:26
You may want to give https://github.com/zachjs/sv2v a shot. It includes support for items at the top level, including imports.

**Comment by gkamendje** [comment] 2020-08-01 19:04
@zachjs  Thanks a lot for the hint. I tried it and it works great so far! I am leaving this issue open hoping that the YOSYS team will integrate top level imports in the near future.

**Comment by nakengelhardt** [comment] 2024-03-25 15:25
duplicate of #4006

**Closed by nakengelhardt** 2024-03-25 15:25 UTC
Labels: enhancement, SystemVerilog
