### ISSUE TITLE
Yosys synthesis Error trying to synthesize verilog from bsc

### ISSUE THREAD

**Issue by shariethernet** [YosysHQ/yosys#2927] opened 2021-08-10 18:44 UTC
Trying to synthesise the below (standard verilog file given by bluespec InOutConnect.v) throws the following error

### Snippet
```verilog
module InoutConnect(
                    .X1(internal),      //ERROR LINE
                    .X2(internal)
                    );
   parameter width = 1;
   inout [ width - 1 : 0 ] internal;
endmodule // InoutConnect

```
### Error Message
```src/InoutConnect.v:3: ERROR: syntax error, unexpected TOK_ID, expecting '.'src/InoutConnect.v:3: ERROR: syntax error, unexpected TOK_ID, expecting '.'```

(I am using Yosys version 0.9+4247)

**Comment by thoughtpolice** [comment] 2021-08-11 19:59
FWIW, this is a duplicate of #2613, and the general feature seems pretty complex. Right now, if you need to connect `inout`'s in this manner, I think you're totally out of luck.

But some support (either a workaround in bsc, or better support in yosys) would be better than nothing. See also: **b-lang-org/bsc#327**

**Closed** 2021-08-13 23:04 UTC
Labels: duplicate
