### ISSUE TITLE
GHDL assertions end up in json, nextpnr complains

### ISSUE THREAD

**Issue by antonblanchard** [YosysHQ/yosys#2068] opened 2020-05-18 22:37 UTC
I'm hitting an issue building microwatt with ghdl/yosys/nextpnr where nextpnr complains about an assertion. I'm not sure if yosys shouldn't emit them, if nextpnr should ignore them, or if they are unsupported and ghdl shouldn't emit them.

A simple example:

```
module test(zot);
input zot;
always @* assert(zot);
endmodule
```

```
yosys -p "read_verilog -sv test.v; synth_ecp5 -json test.json"
nextpnr-ecp5 --um5g-85k --freq 12 --json test.json
```

```
ERROR: cell type '$assert' is unsupported (instantiated as 'zot_$assert_A')
```

**Comment by whitequark** [comment] 2020-05-18 22:48
Duplicate of #177.

**Comment by antonblanchard** [comment] 2020-05-18 23:14
Thanks, I guess the SystemVerilog reproducer was a bit of a red herring. Should GHDL not emit Assert entries at all, or have an option to not emit them? It seems a bit strange to be doing it there, vs yosys or nextpnr.

**Comment by daveshah1** [comment] 2020-05-18 23:30
It wouldn't be too problematic to drop these cells in the nextpnr frontend, if that is the consensus then I'm happy to do that. But I don't know what would happen with synth_xilinx and the EDIF backend, or xilinx/ice40 going into VPR or arachne-pnr via BLIF.

**Comment by whitequark** [comment] 2020-05-18 23:42
Should we perhaps just delete formal cells at the end of every device-specific flow? I'm not sure what the downsides to that are.

**Comment by daveshah1** [comment] 2020-05-18 23:46
Hypothetically I suppose some kind of post-synthesis verification might need them?

**Comment by mikey** [comment] 2020-06-12 05:28
Is there any movement on this? I retested with the latest docker images in ghdl/synth:nextpnr-ecp5 and we are still hitting this.

**Comment by whitequark** [comment] 2020-06-12 07:02
This was rejected in #177.

**Closed by whitequark** 2020-06-12 07:02 UTC
Labels: duplicate

**Comment by antonblanchard** [comment] 2020-06-15 04:00
@whitequark I'm a bit confused, these are runtime asserts in the VHDL, and GHDL is passing them through to yosys. Should we get GHDL to strip them all out?

**Comment by whitequark** [comment] 2020-06-15 04:05
The Verilog backend also passes the asserts through to Yosys. The solution offered in #177 was to use the Verilog preprocessor to strip asserts for synthesis. Does VHDL have one?

**Comment by mikey** [comment] 2020-06-15 04:48
@tgingold @eine is this something we could do in ghdl-synth?

**Comment by tgingold** [comment] 2020-06-15 05:55
1) You can use the `chformal -remove` yosys command to remove all the formal cells.  That's an immediate workaround.
2) We could add a `-no-assert` or `-no-formal` options to the ghdl front-end to disable all the assertions.

**Comment by mikey** [comment] 2020-06-15 07:50
@tgingold IMHO a `-no-assert` would be nicer for microwatt as then we wouldn't need to change our code specifically for ghdl-synth/yosys. We don't use formal at all currently.

**Comment by whitequark** [comment] 2020-06-15 08:14
Wait, you don't use formal? Why do you get assertions in the input netlist then?

**Comment by mikey** [comment] 2020-06-15 21:26
@whitequark we just use asserts. An example that's causing us problems is [here](https://github.com/antonblanchard/microwatt/blob/master/execute1.vhdl#L241).
Happy to take pointers if we are doing this the wrong way.

**Comment by tgingold** [comment] 2020-06-16 05:50
@whitequark The possibility to use assertions in VHDL exists since the first standard (1987) and is not exactly considered as formal methods.

It is now possible to use the `--no-formal` option for synthesis with ghdl.

**Comment by mikey** [comment] 2020-06-22 05:21
@tgingold this works with microwatt. Thanks.

**Comment by mcejp** [comment] 2022-05-20 18:47
FWIW, the equivalent flag for `read_verilog` is `-noassert`
